### ISSUE TITLE
Use timeouts and retries in Invoke-RestMethod

### ISSUE THREAD

**Issue by cuu508** [davehope/HealthChecksIOStatusReport#1]
Consider adding a -TimeoutSec parameter to the Invoke-RestMethod calls – I'd suggest 5-10 seconds. This would be especially important in the "start" call: a stuck HTTP request could block the actual work.

I would also look into using retry parameters (retry count, retry interval). If there is a temporary problem with the ping endpoint (e.g., it returning 503 errors – rare, but not impossible), the client would then retry.

**Comment by davehope** [comment]
Thanks @cuu508 

I'll implement these shortly. I did consider retry options, but was wary as didn't want to end up repeating messages if in fact the first did get through. Any idea if HealthChecksIO support providing a unique ID with a request to prevent such a scenario? (I did read the docs, but couldn't spot anything).

**Comment by cuu508** [comment]
@davehope there's [a feature request for idempotent requests ](https://github.com/healthchecks/healthchecks/issues/319), I'd like to get that implemented but don't have a time frame for it.

Retry can result in duplicate pings if there's packet loss – when the server accepts the request but cannot communicate back the "200 OK". I'm not sure if Invoke-RestMethod would retry in these situations. If it does, I don't think duplicated log entries would be a major problem, it would just look a bit messy.

If the server responds with 400-599 it *has not* accepted the request. So retrying in that case is fine and there would be no risk of duplicated requests.

**Comment by davehope** [comment]
Awesome, thanks.

PowerShell  >= 4.0 support TimeoutSec, so I'll pull a change in for that shortly.

MaximumRetryCount and RetryIntervalSec are supported in PowerShell >= 6.0 for both Invoke-WebRequest and Invoke-RestMethod.

Since PowerShell 5.1 still ships by default with Windows 2019 and >= 4.0 is used in 2012R2 or later i'm not keen to introduce a dependency on more recent PowerShell versions.

**Comment by davehope** [comment]
TimeoutSec introduced in 17e4a069f71927100fc9925a705a61afa0712fb2

**Comment by davehope** [comment]
Closing as fixed, TimeoutSec introduced and used by default.
